name: CI/CD Pipeline

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 20.77.8.205 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no azureuser@20.77.8.205 << 'EOF'
          cd /home/azureuser/fastapi-book-project
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi-book
        EOF
